# Generated by Django 5.2.8 on 2025-11-15 05:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceTaskMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('act', models.CharField(choices=[('Companies Act, 2013', 'Companies Act, 2013'), ('FEMA', 'FEMA'), ('LLP Act 2008', 'LLP Act 2008'), ('CGST ACT 2017', 'CGST ACT 2017'), ('Income Tax Act, 1961', 'Income Tax Act, 1961'), ('ESI Act 1948', 'ESI Act 1948'), ('EPF Act 1952', 'EPF Act 1952'), ('SEBI (LODR)', 'SEBI (LODR)'), ('SEBI', 'SEBI'), ('MSME Act', 'MSME Act')], max_length=255)),
                ('particulars', models.TextField()),
                ('due_date', models.DateField()),
                ('frequency', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Auto', 'Auto'), ('Overdue', 'Overdue'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('company_type', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('last_filed_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('reminder_days', models.IntegerField(default=0)),
                ('penalty_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('consequences', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('evidence_url', models.URLField(blank=True, null=True)),
                ('days_until_due', models.IntegerField(blank=True, null=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('interest_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('penalty', models.CharField(blank=True, max_length=100, null=True)),
                ('late_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('interest_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('task_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Task Master',
                'verbose_name_plural': 'Compliance Task Masters',
                'db_table': 'compliance_task_master',
            },
        ),
        migrations.CreateModel(
            name='CompliancePayments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('payment_type', models.CharField(max_length=100)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateField()),
                ('amount', models.CharField(max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('related_act', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('days_early_or_late', models.IntegerField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('estimated_penalty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('estimated_interest', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('estimated_late_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('compliance_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_payments', to='compliance.compliancetaskmaster')),
            ],
            options={
                'verbose_name': 'Compliance Payment',
                'verbose_name_plural': 'Compliance Payments',
                'db_table': 'compliance_payments',
            },
        ),
    ]
