# Generated by Django 5.2.8 on 2025-11-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancetaskmaster',
            name='status',
            field=models.CharField(choices=[('Overdue', 'Overdue'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('In Progress', 'In Progress')], default='Pending', max_length=50),
        ),
    ]
