# Generated by Django 5.2.8 on 2025-11-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_first_name_alter_user_last_name'),
        ('compliance', '0003_compliancetaskmaster_is_admin_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancetaskmaster',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Companies that have selected this task. Only selected tasks are displayed for each company.', related_name='selected_compliance_tasks', to='accounts.company'),
        ),
    ]
