# Generated by Django 5.2.8 on 2025-11-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_compliancetaskmaster_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancetaskmaster',
            name='frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half-yearly', 'Half-yearly'), ('Annually', 'Annually')], max_length=100),
        ),
    ]
