# Generated by Django 5.2.8 on 2025-11-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_alter_compliancetaskmaster_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancetaskmaster',
            name='payment_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
