# Generated by Django 5.2.8 on 2025-11-27 10:29

import re

from django.db import migrations, models


def sanitize_payment_amount(apps, schema_editor):
    Task = apps.get_model('compliance', 'ComplianceTaskMaster')
    qs = Task.objects.exclude(payment_amount__isnull=True).exclude(payment_amount="")
    for task in qs.iterator(chunk_size=500):
        cleaned = re.sub(r"[^\d\.\-]", "", task.payment_amount or "")
        task.payment_amount = cleaned or None
        task.save(update_fields=["payment_amount"])


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_compliancetaskmaster_payment_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancetaskmaster',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(sanitize_payment_amount, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='compliancetaskmaster',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
