# Generated by Django 5.2.8 on 2025-12-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_compliancetaskmaster_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancetaskmaster',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Bank Transfer', 'Bank Transfer'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('Cheque', 'Cheque'), ('UPI', 'UPI'), ('Cash', 'Cash'), ('Credit card', 'Credit card')], max_length=100, null=True),
        ),
    ]
