# Generated by Django 5.2.8 on 2025-11-18 10:39

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapTableEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('Incorporation', 'Incorporation'), ("Founders' Equity", "Founders' Equity"), ('Seed Round', 'Seed Round'), ('Series A', 'Series A'), ('Series B', 'Series B'), ('Series C', 'Series C'), ('Series D', 'Series D'), ('ESOP Grant', 'ESOP Grant'), ('Secondary Sale', 'Secondary Sale'), ('Other', 'Other')], max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_raised', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('share_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cap_table_events', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cap Table Event',
                'verbose_name_plural': 'Cap Table Events',
                'db_table': 'captable_events',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CapTableEventDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='captable/events/%Y/%m/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='captable.captableevents')),
            ],
            options={
                'db_table': 'captable_event_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('investor_type', models.CharField(choices=[('Founder', 'Founder'), ('Angel Investor', 'Angel Investor'), ('Venture Capital', 'Venture Capital'), ('Strategic Investment', 'Strategic Investment'), ('Advisor', 'Advisor'), ('Employee', 'Employee'), ('Other', 'Other')], default='Other', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'captable_shareholder',
                'ordering': ['name'],
                'unique_together': {('company', 'email')},
            },
        ),
        migrations.CreateModel(
            name='CapitalizationTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('share_class_type', models.CharField(choices=[('Common', 'Common'), ('Preference', 'Preference'), ('Debenture', 'Debenture'), ('Advisory', 'Advisory'), ('ESOP', 'ESOP')], max_length=255)),
                ('share_class_name', models.CharField(max_length=255)),
                ('shares_issued', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lock_in_ends', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitalization_rows', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='captable.captableevents')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='captable.shareholder')),
            ],
            options={
                'verbose_name': 'Capitalization Table',
                'verbose_name_plural': 'Capitalization Tables',
                'db_table': 'captable_capitalization_table',
                'ordering': ['-event__date'],
            },
        ),
    ]
