# Generated by Django 5.2.8 on 2025-11-28 07:05

import captable.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_first_name_alter_user_last_name'),
        ('captable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ESOPGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_email', models.EmailField(max_length=254)),
                ('grant_date', models.DateField(validators=[captable.models.validate_not_future])),
                ('cliff_date', models.DateField(validators=[captable.models.validate_future_only])),
                ('total_options', models.PositiveIntegerField()),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fair_market_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exercise_window_days', models.PositiveIntegerField()),
                ('vesting_schedule', models.TextField()),
                ('grant_type', models.CharField(choices=[('Stock Options', 'Stock Options'), ('RSU', 'RSU'), ('SAR', 'SAR')], default='Stock Options', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Exercised', 'Exercised')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esop_grants', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ESOP Grant',
                'verbose_name_plural': 'ESOP Grants',
                'db_table': 'captable_esop_grant',
                'ordering': ['-grant_date'],
                'constraints': [models.UniqueConstraint(fields=('company', 'employee_email', 'grant_date'), name='unique_esop_per_employee_per_company_per_grant_date')],
            },
        ),
    ]
