# Generated by Django 5.2.8 on 2025-11-28 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_first_name_alter_user_last_name'),
        ('captable', '0002_esopgrant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VestingSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('total_shares', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('vesting_frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annual', 'Semi-Annual'), ('Annual', 'Annual')], default='Monthly', max_length=20)),
                ('cliff_period_months', models.PositiveIntegerField()),
                ('total_vesting_period_months', models.PositiveIntegerField()),
                ('single_trigger', models.BooleanField(default=False)),
                ('double_trigger', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vesting_schedules', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vesting Schedule',
                'verbose_name_plural': 'Vesting Schedules',
                'db_table': 'captable_vesting_schedule',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='esopgrant',
            name='vesting_schedule_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esop_grants', to='captable.vestingschedule'),
        ),
        migrations.AddConstraint(
            model_name='vestingschedule',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_vesting_schedule_per_company'),
        ),
    ]
