# Generated by Django 5.2.8 on 2025-12-01 05:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_face_value_per_share'),
        ('captable', '0003_vestingschedule_esopgrant_vesting_schedule_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ESOPPoolHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('POOL_CREATED', 'Pool Created'), ('POOL_EXPANDED', 'Pool Expanded'), ('POOL_REDUCED', 'Pool Reduced')], default='POOL_CREATED', max_length=50)),
                ('event_date', models.DateField()),
                ('pool_size_before', models.PositiveIntegerField(default=0)),
                ('pool_size_after', models.PositiveIntegerField(default=0)),
                ('pool_percentage_before', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('pool_percentage_after', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('change_amount', models.IntegerField(help_text='Change in pool size (positive for increase, negative for decrease)')),
                ('description', models.TextField(blank=True, help_text='Description of the change')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the change', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esop_pool_history', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ESOP Pool History',
                'verbose_name_plural': 'ESOP Pool Histories',
                'db_table': 'captable_esop_pool_history',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
