# Generated by Django 5.2.8 on 2025-12-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captable', '0004_esoppoolhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitalizationtable',
            options={'ordering': ['event__date'], 'verbose_name': 'Capitalization Table', 'verbose_name_plural': 'Capitalization Tables'},
        ),
        migrations.AlterModelOptions(
            name='captableevents',
            options={'ordering': ['date'], 'verbose_name': 'Cap Table Event', 'verbose_name_plural': 'Cap Table Events'},
        ),
    ]
