# Generated by Django 5.2.8 on 2025-12-03 12:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminderrule',
            name='company',
        ),
        migrations.RemoveField(
            model_name='reminderrule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reminderrule',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('500000.00'), help_text='Maximum credit limit extended to the customer (editable)', max_digits=14),
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
        migrations.DeleteModel(
            name='ReminderRule',
        ),
    ]
