# Generated by Django 5.2.8 on 2025-12-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_billpayment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='updated_by',
        ),
    ]
