# Generated by Django 5.2.8 on 2025-12-10 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_alter_invoice_unique_together_remove_invoice_company_and_more'),
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='revenue.invoice'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='matched_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_transactions', to='revenue.invoice'),
        ),
        migrations.AlterField(
            model_name='factoringrequestinvoice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factoring_requests', to='revenue.invoice'),
        ),
        migrations.AlterField(
            model_name='writeoff',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_offs', to='revenue.invoice'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='revenue.invoice'),
        ),
        migrations.AlterField(
            model_name='dunningqueue',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_queues', to='revenue.invoice'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
