# Generated by Django 5.2.8 on 2025-12-12 12:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_face_value_per_share'),
        ('financial', '0006_alter_paymentplan_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='amount',
        ),
        migrations.AddField(
            model_name='bill',
            name='branch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bill',
            name='branch_gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='bill',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='CGST Amount = CGST % * SubTotal', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='bill',
            name='cgst_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='CGST percentage (e.g., 9.00 for 9%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='bill',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='eligibility',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='hsn_sac',
            field=models.CharField(blank=True, help_text='HSN/SAC Code', max_length=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IGST Amount = IGST % * SubTotal', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='bill',
            name='igst_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IGST percentage (e.g., 18.00 for 18%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this is a recurring bill'),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_vendor_out_of_india',
            field=models.BooleanField(default=False, help_text='Check if vendor is outside India'),
        ),
        migrations.AddField(
            model_name='bill',
            name='item_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('COD', 'COD'), ('Net 7', 'Net 7'), ('Net 15', 'Net 15'), ('Net 30', 'Net 30'), ('Net 45', 'Net 45'), ('Net 60', 'Net 60'), ('Net 90', 'Net 90')], help_text='Payment terms (e.g., Net 30)', max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bill',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SGST Amount = SGST % * SubTotal', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='bill',
            name='sgst_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SGST percentage (e.g., 9.00 for 9%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='bill',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal before taxes', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='bill',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='TDS Amount = TDS % * SubTotal', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='bill',
            name='tds_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='TDS percentage (e.g., 2.00 for 2%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='bill',
            name='tds_section',
            field=models.CharField(blank=True, help_text='TDS Section (e.g., 194A, 194C)', max_length=50),
        ),
        migrations.AddField(
            model_name='bill',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total = SubTotal + CGST + SGST + IGST - TDS', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='bill',
            name='vendor_gstin',
            field=models.CharField(blank=True, help_text='Vendor GST Identification Number', max_length=15),
        ),
        migrations.AddField(
            model_name='bill',
            name='vendor_pan',
            field=models.CharField(blank=True, help_text='Vendor PAN Number', max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_bills', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_bills', to='financial.vendor'),
        ),
        migrations.AlterModelTable(
            name='bill',
            table='expense_bill',
        ),
    ]
