# Generated by Django 5.2.8 on 2025-12-17 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0002_bill"),  # Ensure expense.Bill exists in migration state
        ("financial", "0007_remove_bill_amount_bill_branch_bill_branch_gstin_and_more"),
    ]

    operations = [
        # Delete the old Bill model from state first
        migrations.DeleteModel(
            name="Bill",
        ),
        # Alter the field reference using SeparateDatabaseAndState
        # This ensures we only update the state, not the database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="billpayment",
                    name="bill",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="expense.Bill",
                    ),
                ),
            ],
            # No database operations - SQLite doesn't enforce FK constraints
            # The table structure doesn't need to change
            database_operations=[],
        ),
    ]
