# Generated by Django 5.2.8 on 2025-12-09 11:31

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_face_value_per_share'),
        ('hr', '0002_headcount_benefits_annual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in progress', 'In Progress'), ('filled', 'Filled')], default='open', max_length=50)),
                ('positions_required', models.PositiveIntegerField(default=1)),
                ('applications_received', models.PositiveIntegerField(default=0)),
                ('interviews_conducted', models.PositiveIntegerField(default=0)),
                ('offers_made', models.PositiveIntegerField(default=0)),
                ('offers_accepted', models.PositiveIntegerField(default=0)),
                ('cost_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('source', models.CharField(blank=True, choices=[('Company Website', 'Company Website'), ('Campus Hiring', 'Campus Hiring'), ('LinkedIn', 'LinkedIn'), ('Naukri', 'Naukri'), ('Employee Referral', 'Employee Referral'), ('Agency', 'Agency'), ('Job Board', 'Job Board'), ('Other', 'Other')], max_length=100, null=True)),
                ('posting_date', models.DateField()),
                ('target_close_date', models.DateField(blank=True, null=True)),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('salary_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('salary_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitments', to='hr.department')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruitment',
                'verbose_name_plural': 'Recruitments',
                'db_table': 'recruitment',
                'ordering': ['-posting_date'],
            },
        ),
    ]
