# Generated by Django 5.2.8 on 2025-11-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_image_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='nature_of_business',
            field=models.CharField(choices=[('SaaS', 'SaaS'), ('Ecommerce', 'Ecommerce'), ('Services Provider', 'Services Provider'), ('Manufacturer', 'Manufacturer')], default='SaaS', max_length=100),
        ),
    ]
