# Generated by Django 5.2.8 on 2025-11-29 06:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='authorized_capital_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Authorized Capital in currency', max_digits=20),
        ),
        migrations.AddField(
            model_name='company',
            name='authorized_capital_shares',
            field=models.PositiveIntegerField(default=0, help_text='Number of authorized shares'),
        ),
        migrations.AddField(
            model_name='company',
            name='esop_pool_notes',
            field=models.TextField(blank=True, help_text='Notes about ESOP pool configuration', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='esop_pool_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='ESOP Pool as percentage of authorized shares', max_digits=5),
        ),
        migrations.AddField(
            model_name='company',
            name='esop_pool_size',
            field=models.PositiveIntegerField(default=0, help_text='ESOP Pool size in number of shares'),
        ),
        migrations.AddField(
            model_name='company',
            name='issued_capital_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Issued Capital in currency', max_digits=20),
        ),
        migrations.AddField(
            model_name='company',
            name='issued_capital_shares',
            field=models.PositiveIntegerField(default=0, help_text='Number of issued shares'),
        ),
        migrations.AddField(
            model_name='company',
            name='paid_up_capital_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Paid-up Capital in currency', max_digits=20),
        ),
        migrations.AddField(
            model_name='company',
            name='paid_up_capital_shares',
            field=models.PositiveIntegerField(default=0, help_text='Number of paid-up shares'),
        ),
        migrations.AddField(
            model_name='company',
            name='securities_premium',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Securities Premium (Share Premium Account)', max_digits=20),
        ),
    ]
