# Generated by Django 5.2.8 on 2025-11-29 07:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_authorized_capital_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='face_value_per_share',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Face value per share (used to calculate capital amounts)', max_digits=20),
        ),
    ]
