# Generated by Django 5.2.8 on 2025-12-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled'), ('Bad Debt', 'Bad Debt'), ('Sent', 'Sent')], default='Draft', max_length=20),
        ),
    ]
