from revenue.views.api.register import (
    AllInvoicesView,
    CustomerRevenueView,
    CustomerInvoicesView,
    ProductRevenueView,
    ProductInvoicesView,
    SalespersonRevenueView,
    SalespersonInvoicesView,
    ServiceRevenueView,
    ServiceInvoicesView,
)
from revenue.views.api.import_invoices import RevenueInvoiceImportView
from revenue.views.api.analytics import (
    TrendsYearOverYearView,
    TrendsServiceKPIsView,
    CustomersOverviewView,
    CustomersCohortAnalysisView,
    SalespersonOverviewView,
    SalespersonPerformanceView,
    ProductsOverviewView,
    ProductsDetailsView,
    BranchOverviewView,
    BranchPerformanceView,
    GeographicOverviewView,
    GeographicDetailsView,
    GSTOverviewView,
    RevenueDashboardView,
)

__all__ = [
    "AllInvoicesView",
    "CustomerRevenueView",
    "CustomerInvoicesView",
    "ProductRevenueView",
    "ProductInvoicesView",
    "SalespersonRevenueView",
    "SalespersonInvoicesView",
    "ServiceRevenueView",
    "ServiceInvoicesView",
    "RevenueInvoiceImportView",
    "TrendsYearOverYearView",
    "TrendsServiceKPIsView",
    "CustomersOverviewView",
    "CustomersCohortAnalysisView",
    "SalespersonOverviewView",
    "SalespersonPerformanceView",
    "ProductsOverviewView",
    "ProductsDetailsView",
    "BranchOverviewView",
    "BranchPerformanceView",
    "GeographicOverviewView",
    "GeographicDetailsView",
    "GSTOverviewView",
    "RevenueDashboardView",
]
