# Generated by Django 5.2.8

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0006_company_face_value_per_share"),
        ("financial", "0007_remove_bill_amount_bill_branch_bill_branch_gstin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringExpense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the recurring expense (e.g., 'Software Subscription')",
                        max_length=255,
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(
                        blank=True,
                        help_text="Vendor/Service name (e.g., AWS, HubSpot, WeWork)",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the recurring expense",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Expense category (e.g., Technology & Infrastructure, Personnel Expenses)",
                        max_length=255,
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        blank=True,
                        help_text="Sub-category (e.g., Productivity Tools)",
                        max_length=255,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        help_text="Base amount of the recurring expense",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        help_text="Tax amount",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Semi-annual", "Semi-annual"),
                            ("Annual", "Annual"),
                        ],
                        default="Monthly",
                        help_text="How often the expense recurs",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Start date of the recurring expense",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        help_text="End date of the contract (optional)",
                    ),
                ),
                (
                    "contract_reference",
                    models.CharField(
                        blank=True,
                        help_text="Contract ID or reference",
                        max_length=255,
                    ),
                ),
                (
                    "auto_generate_expenses",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create expense entries when due",
                    ),
                ),
                (
                    "days_before_due_to_generate",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Number of days before due date to generate the expense",
                    ),
                ),
                (
                    "renewal_reminder_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Number of days before renewal to send reminder",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Expired", "Expired"),
                            ("Cancelled", "Cancelled"),
                            ("Paused", "Paused"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_expenses",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_expenses",
                        to="financial.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring Expense",
                "verbose_name_plural": "Recurring Expenses",
                "db_table": "expense_recurring_expense",
                "ordering": ["-created_at"],
            },
        ),
    ]
