# Generated by Django 5.2.8 on 2025-12-17 17:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_company_face_value_per_share"),
        ("expense", "0001_initial"),
        ("financial", "0008_alter_billpayment_bill_delete_bill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        help_text="Expense category (e.g., Technology & Infrastructure, Personnel Expenses)",
                        max_length=255,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Department name (optional)",
                        max_length=255,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Semi-annual", "Semi-annual"),
                            ("Annual", "Annual"),
                        ],
                        default="Monthly",
                        help_text="Period type for this budget (Monthly, Quarterly, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "period",
                    models.DateField(
                        help_text="Start date of the budget period (e.g., 2025-12-01 for December 2025)"
                    ),
                ),
                (
                    "budget_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Budgeted amount for this period",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this budget"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_budgets",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Budget",
                "verbose_name_plural": "Expense Budgets",
                "db_table": "expense_budget",
                "ordering": ["-period", "category", "department"],
                "unique_together": {
                    ("company", "category", "department", "period_type", "period")
                },
            },
        ),
    ]
