# Generated by Django 5.2.8 on 2025-12-18 03:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_company_face_value_per_share"),
        ("expense", "0002_bill_expensebudget"),
        ("financial", "0008_alter_billpayment_bill_delete_bill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bill_number", models.CharField(max_length=100)),
                ("bill_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "vendor_name",
                    models.CharField(
                        blank=True,
                        help_text="Legacy field, use vendor FK when possible",
                        max_length=255,
                    ),
                ),
                (
                    "vendor_gstin",
                    models.CharField(
                        blank=True,
                        help_text="Vendor GST Identification Number",
                        max_length=15,
                    ),
                ),
                (
                    "vendor_pan",
                    models.CharField(
                        blank=True, help_text="Vendor PAN Number", max_length=10
                    ),
                ),
                (
                    "is_vendor_out_of_india",
                    models.BooleanField(
                        default=False, help_text="Check if vendor is outside India"
                    ),
                ),
                ("item_name", models.CharField(blank=True, max_length=255)),
                (
                    "hsn_sac",
                    models.CharField(
                        blank=True, help_text="HSN/SAC Code", max_length=10
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("place_of_supply", models.CharField(blank=True, max_length=255)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Subtotal before taxes",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "cgst_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="CGST percentage (e.g., 9.00 for 9%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="CGST Amount = CGST % * SubTotal",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "sgst_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="SGST percentage (e.g., 9.00 for 9%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="SGST Amount = SGST % * SubTotal",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "igst_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="IGST percentage (e.g., 18.00 for 18%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "igst_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="IGST Amount = IGST % * SubTotal",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tds_section",
                    models.CharField(
                        blank=True,
                        help_text="TDS Section (e.g., 194A, 194C)",
                        max_length=50,
                    ),
                ),
                (
                    "tds_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="TDS percentage (e.g., 2.00 for 2%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tds_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="TDS Amount = TDS % * SubTotal",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total = SubTotal + CGST + SGST + IGST - TDS",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COD", "COD"),
                            ("Net 7", "Net 7"),
                            ("Net 15", "Net 15"),
                            ("Net 30", "Net 30"),
                            ("Net 45", "Net 45"),
                            ("Net 60", "Net 60"),
                            ("Net 90", "Net 90"),
                        ],
                        help_text="Payment terms (e.g., Net 30)",
                        max_length=100,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Partial", "Partial"),
                            ("Paid", "Paid"),
                            ("Overdue", "Overdue"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("branch", models.CharField(blank=True, max_length=255)),
                ("branch_gstin", models.CharField(blank=True, max_length=15)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("eligibility", models.CharField(blank=True, max_length=100)),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False, help_text="Whether this is a recurring bill"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_bills",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_bills",
                        to="financial.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill",
                "verbose_name_plural": "Bills",
                "db_table": "expense_bill",
                "ordering": ["-bill_date"],
                "unique_together": {("company", "bill_number")},
            },
        ),
    ]
