# Generated by GitHub Copilot to fix missing expense_bill table
from django.db import migrations, connection
from django.conf import settings


def create_expense_bill_if_missing(apps, schema_editor):
    table_name = "expense_bill"
    existing_tables = set(connection.introspection.table_names())
    if table_name in existing_tables:
        return

    Bill = apps.get_model("expense", "Bill")
    # Use the provided schema_editor to create the model table and constraints
    schema_editor.create_model(Bill)


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0003_expensebudget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_expense_bill_if_missing, migrations.RunPython.noop),
    ]
