# Generated by Django 5.2.8 on 2025-11-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0003_alter_folder_unique_together_alter_folder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('view', 'view'), ('download', 'download'), ('create', 'create'), ('update', 'update'), ('delete', 'delete'), ('list', 'list'), ('retrieve', 'retrieve')], max_length=20),
        ),
    ]
