# Generated by Django 5.2.8 on 2025-11-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0004_accesslog_endpoint_accesslog_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslog',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='method',
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('view', 'view'), ('download', 'download')], max_length=20),
        ),
    ]
