# Generated by Django 5.2.8 on 2025-11-13 12:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_number', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('GST', 'GST'), ('Income Tax', 'Income Tax'), ('Professional Tax', 'Professional Tax'), ('ESI', 'ESI'), ('PF', 'PF'), ('Labour', 'Labour'), ('Commercial', 'Commercial'), ('Other', 'Other')], max_length=30)),
                ('synopsis', models.TextField(blank=True)),
                ('total_exposure', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('in progress', 'in progress'), ('appealed', 'appealed'), ('stayed', 'stayed'), ('resolved', 'resolved'), ('closed', 'closed'), ('dismissed', 'dismissed')], default='open', max_length=20)),
                ('risk', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], default='low', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'litigation_case',
                'indexes': [models.Index(fields=['company', 'type'], name='litigation__company_e4ed67_idx'), models.Index(fields=['company', 'status'], name='litigation__company_27805f_idx'), models.Index(fields=['company', 'risk'], name='litigation__company_29c2bc_idx')],
            },
        ),
    ]
