# Generated by Django 5.2.8 on 2025-11-17 10:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='act_section',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='case',
            name='authority',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='consultant_contact',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='case',
            name='consultant_firm',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='case',
            name='consultant_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='case',
            name='demand_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='case',
            name='designation',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='case',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='hearing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='case',
            name='internal_responsible_person',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='case',
            name='likelihood_of_success',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='case',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='case',
            name='provision_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='case',
            name='resolution_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='responsible_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='case',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
