# Generated by Django 5.2.8 on 2025-12-06 04:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_company_face_value_per_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal_id', models.CharField(max_length=100)),
                ('deal_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('mrr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly Recurring Revenue', max_digits=12)),
                ('stage', models.CharField(choices=[('Discovery', 'Discovery'), ('Qualification', 'Qualification'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost'), ('Unqualified', 'Unqualified')], default='Discovery', max_length=50)),
                ('client', models.CharField(max_length=255)),
                ('sales_team', models.CharField(max_length=255)),
                ('probability', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Probability percentage of closing the deal (0-100)', max_digits=5)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('subscription_product', models.CharField(blank=True, choices=[('Enterprise', 'Enterprise'), ('Pro', 'Pro'), ('Starter', 'Starter')], max_length=50, null=True)),
                ('contract_term_months', models.PositiveIntegerField(blank=True, help_text='Duration of the contract in months', null=True)),
                ('days_in_stage', models.PositiveIntegerField(default=0, help_text='Number of days the deal has been in the current stage')),
                ('last_activity', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('Outbound', 'Outbound'), ('Inbound', 'Inbound'), ('Referral', 'Referral'), ('Event', 'Event'), ('Partner', 'Partner'), ('Social Media', 'Social Media'), ('Other', 'Other')], help_text='Source of the lead/deal', max_length=50, null=True)),
                ('next_step', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Lost', 'Lost'), ('Contract Review', 'Contract Review'), ('Legal Review', 'Legal Review'), ('Pricing Discussion', 'Pricing Discussion'), ('Final Approval', 'Final Approval'), ('Proposal Presentation', 'Proposal Presentation'), ('Technical Validation', 'Technical Validation'), ('ROI Presentation', 'ROI Presentation'), ('Demo Follow-up', 'Demo Follow-up'), ('Discovery Call', 'Discovery Call'), ('Technical Scoping', 'Technical Scoping'), ('Stakeholder Mapping', 'Stakeholder Mapping'), ('Initial Assessment', 'Initial Assessment'), ('Intro Meeting Scheduled', 'Intro Meeting Scheduled'), ('Demo Scheduled', 'Demo Scheduled'), ('Initial Contact', 'Initial Contact'), ('Qualification Call', 'Qualification Call')], help_text='Next action step in the sales process', max_length=50, null=True)),
                ('lost_reason', models.TextField(blank=True, null=True)),
                ('competitors', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'sales',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'deal_id')},
            },
        ),
    ]
