# Generated by Django 5.2.8 on 2025-12-06 05:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_face_value_per_share'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_id', models.CharField(blank=True, help_text='Employee ID or unique identifier', max_length=100, null=True)),
                ('designation', models.CharField(blank=True, help_text='Job title or designation', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the team member is currently active')),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_teams', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Team Member',
                'verbose_name_plural': 'Sales Team Members',
                'db_table': 'sales_team',
                'ordering': ['name'],
                'unique_together': {('company', 'email')},
            },
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_team',
            field=models.ForeignKey(blank=True, help_text='Sales team member assigned to this deal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.salesteam'),
        ),
    ]
